# Generated by Django 4.0.1 on 2022-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measure_photo_alter_sensor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
