# Generated by Django 4.0.1 on 2022-02-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='measurement.sensor'),
        ),
    ]
