# Generated by Django 4.0.1 on 2022-02-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measure_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
